In [47]:
import pandas as pd

In [48]:
df=pd.read_csv('../train_prepared.csv')
df.head()

,region,parent_category_name,category_name,param_1,param_2,param_3,price,item_seq_number,user_type,deal_probability,has_params,description_len,description_group
0,Свердловская область,Личные вещи,Товары для детей и игрушки,1,0,0,400.0,2,Private,0.12789,1,58,3. Оптимальное
1,Самарская область,Для дома и дачи,Мебель и интерьер,1,0,0,3000.0,19,Private,0.00000,1,41,2. Очень короткое
2,Ростовская область,Бытовая электроника,Аудио и видео,1,0,0,4000.0,9,Private,0.43177,1,99,3. Оптимальное
3,Татарстан,Личные вещи,Товары для детей и игрушки,1,0,0,2200.0,286,Company,0.80323,1,22,2. Очень короткое
4,Волгоградская область,Транспорт,Автомобили,1,1,1,40000.0,3,Private,0.20797,1,24,2. Очень короткое

In [49]:
# Показывает медиану, 25% и 75% квантили для количества объявлений
df.groupby('category_name')['category_name'].count().describe()

count      47.000000
mean     1046.106383
std      1852.388437
min         2.000000
25%       229.000000
50%       362.000000
75%       940.500000
max      9232.000000
Name: category_name, dtype: float64

In [ ]:
liq_low_ad=df.groupby('category_name')[['category_name','deal_probability']].agg(
    num_of_ad=('category_name', 'count'),
    avg_probability=('deal_probability', 'mean')
).reset_index()
liq_low_ad=liq_low_ad.query("num_of_ad<362")
liq_low_ad=liq_low_ad.sort_values(by='avg_probability', ascending=False)
liq_low_ad

                   category_name  num_of_ad  avg_probability
34             Предложение услуг       2199         0.401384
0                     Автомобили       2055         0.282467
20                         Кошки        362         0.281867
12               Другие животные        371         0.254970
23       Мотоциклы и мототехника        202         0.252895
4                Бытовая техника       1132         0.249592
39                        Собаки        393         0.245173
5                     Велосипеды        321         0.235502
36                         Птицы        197         0.234093
6               Водный транспорт         80         0.207939
42    Товары для детей и игрушки       3200         0.204254
14   Игры, приставки и программы        378         0.201846
27                      Ноутбуки        332         0.197780
22             Мебель и интерьер       2154         0.192417
24       Музыкальные инструменты        220         0.187979
9        Грузовики и спецтехника        324         0.186671
30       Оргтехника и расходники        221         0.184171
41                      Телефоны       2274         0.180262
25         Настольные компьютеры        157         0.178897
32  Планшеты и электронные книги        284         0.174359
19                       Комнаты        267         0.173404
2                  Аудио и видео        870         0.168191
44         Товары для компьютера        998         0.160657
15                      Квартиры       2662         0.156907
43           Товары для животных        256         0.156865
40                 Спорт и отдых        840         0.150185
1                       Аквариум        161         0.144246
7           Гаражи и машиноместа        257         0.140387
31               Охота и рыбалка        156         0.139285
38        Ремонт и строительство       1852         0.138220
35              Продукты питания        197         0.136037
37                      Растения        283         0.124725
26       Недвижимость за рубежом          2         0.121475
11          Дома, дачи, коттеджи        927         0.120828
3           Билеты и путешествия         96         0.116201
45                   Фототехника        237         0.112347
28      Оборудование для бизнеса        493         0.111410
33     Посуда и товары для кухни        300         0.101486
18     Коммерческая недвижимость        306         0.100428
8                 Готовый бизнес         70         0.092760
21            Красота и здоровье        954         0.090701
13             Земельные участки        545         0.088697
10        Детская одежда и обувь       8693         0.064468
17            Коллекционирование        788         0.056273
46              Часы и украшения        486         0.048777
29     Одежда, обувь, аксессуары       9232         0.048346
16               Книги и журналы        383         0.035105